version: "3.8"

services:
    database:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build: ./backend
        ports:
            - "3001:3001"
        environment:
            - NODE_ENV=${NODE_ENV}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - ./backend:/app
            - /app/node_modules

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        depends_on:
            - backend
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next

volumes:
    postgres_data:
